// Generated by scripts/convert-art.mjs from design/components/TreasureChest.dc.html — do not edit by hand.
/* eslint-disable */
class DCLogic { constructor(props) { this.props = props || {}; this.state = {}; } setState() {} }
class Component extends DCLogic {
  renderVals() {
    const open = !!(this.props.open ?? false);
    return { open, closed: !open };
  }
}
const tpl = (v) => `<div style="width: 180px; height: 150px; position: relative;">
<svg width="180" height="150" viewBox="0 0 180 150" style="display: block; overflow: visible;">
<defs>
<radialGradient id="tc-glow"><stop offset="0" stop-color="#FFF1B8" stop-opacity="0.95"></stop><stop offset="1" stop-color="#F5B82E" stop-opacity="0"></stop></radialGradient>
<linearGradient id="tc-lac" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2A1E24"></stop><stop offset="1" stop-color="#110B0E"></stop></linearGradient>
</defs>
<ellipse cx="90" cy="141" rx="72" ry="7" fill="#000000" opacity="0.4"></ellipse>
${(v.open) ? `
<g>
<g class="spin-slow" style="transform-box: view-box; transform-origin: 90px 64px;" opacity="0.8">
<path d="M90 64 L40 -46 L66 -50 Z" fill="#FFE58A" opacity="0.5"></path>
<path d="M90 64 L92 -60 L116 -54 Z" fill="#FFE58A" opacity="0.55"></path>
<path d="M90 64 L150 -40 L170 -26 Z" fill="#FFE58A" opacity="0.45"></path>
<path d="M90 64 L4 -2 L14 -24 Z" fill="#FFE58A" opacity="0.4"></path>
<path d="M90 64 L186 6 L178 -18 Z" fill="#FFE58A" opacity="0.4"></path>
</g>
<ellipse cx="90" cy="64" rx="92" ry="62" fill="url(#tc-glow)"></ellipse>
<path d="M26 72 L36 12 Q90 -4 144 12 L154 72 Z" fill="#110B0E" stroke="#0B0B14" stroke-width="4" stroke-linejoin="round"></path>
<path d="M38 66 L46 22 Q90 12 134 22 L142 66 Z" fill="#7A1411"></path>
<path d="M36 12 L44 24 M144 12 L136 24" stroke="#F5B82E" stroke-width="4"></path>
<g stroke="#0B0B14" stroke-width="2">
<circle cx="64" cy="66" r="11" fill="#F5B82E"></circle>
<circle cx="88" cy="60" r="12" fill="#FFD43B"></circle>
<circle cx="114" cy="66" r="11" fill="#F5B82E"></circle>
<rect x="60" y="62" width="8" height="8" fill="#0B0B14"></rect>
<rect x="84" y="56" width="8" height="8" fill="#0B0B14"></rect>
<rect x="110" y="62" width="8" height="8" fill="#0B0B14"></rect>
<path d="M98 50 L120 34 L126 42 L104 58 Z" fill="#F1E3C8"></path>
<path d="M118 36 L124 32 L130 40 L126 42 Z" fill="#B42318"></path>
<path d="M70 48 L78 38 L86 48 L78 58 Z" fill="#20C997"></path>
</g>
</g>
` : ''}
<path d="M22 72 h136 v58 a6 6 0 0 1 -6 6 H28 a6 6 0 0 1 -6 -6 Z" fill="url(#tc-lac)" stroke="#0B0B14" stroke-width="4" stroke-linejoin="round"></path>
<path d="M32 82 H148 V126 H32 Z" fill="none" stroke="#B42318" stroke-width="3"></path>
<path d="M22 72 h18 v18 M158 72 h-18 v18 M22 136 v-18 h18 M158 136 v-18 h-18" stroke="#F5B82E" stroke-width="5" fill="none"></path>
<path d="M30 76 Q90 70 150 76" stroke="#FFFFFF" stroke-opacity="0.15" stroke-width="3" fill="none"></path>
${(v.closed) ? `
<g>
<path d="M20 76 L20 52 Q20 20 90 20 Q160 20 160 52 L160 76 Z" fill="#1E1418" stroke="#0B0B14" stroke-width="4" stroke-linejoin="round"></path>
<path d="M30 40 Q90 26 150 40" fill="none" stroke="#FFFFFF" stroke-opacity="0.18" stroke-width="4" stroke-linecap="round"></path>
<path d="M20 60 h20 M160 60 h-20" stroke="#F5B82E" stroke-width="5"></path>
<circle cx="90" cy="44" r="15" fill="#B42318" stroke="#F5B82E" stroke-width="3"></circle>
<circle cx="85" cy="40" r="4" fill="#F5B82E"></circle><circle cx="95" cy="40" r="4" fill="#F5B82E"></circle><circle cx="90" cy="49" r="4" fill="#F5B82E"></circle>
<rect x="78" y="66" width="24" height="28" rx="4" fill="#F5B82E" stroke="#0B0B14" stroke-width="3"></rect>
<path d="M90 74 a4 4 0 1 1 0.1 0 z M88 77 h4 l1 9 h-6 z" fill="#0B0B14"></path>
</g>
` : ''}
${(v.open) ? `
<g>
<rect x="78" y="70" width="24" height="20" rx="4" fill="#F5B82E" stroke="#0B0B14" stroke-width="3"></rect>
<path d="M12 36 l3 -8 l3 8 l8 3 l-8 3 l-3 8 l-3 -8 l-8 -3 z" fill="#FFFFFF"></path>
<path d="M162 24 l2 -6 l2 6 l6 2 l-6 2 l-2 6 l-2 -6 l-6 -2 z" fill="#FFFFFF"></path>
</g>
` : ''}
</svg>
</div>`;
export default function render(props = {}) {
  const v = new Component(props).renderVals();
  return tpl(v);
}
