// Converts the Design-canvas art components (design/components/*.dc.html)
// into plain JS render functions (src/art/*.js) used by the game.
// Template holes {{a.b}} become ${v.a.b}; <sc-if>/<sc-for> become JS conditionals/maps;
// each component's renderVals() logic is reused as-is through a tiny DCLogic shim.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const SRC = 'design/components';
const OUT = 'src/art';

function convertMarkup(markup) {
  const loopVars = [];
  const stack = [];
  let out = '';
  const re = /<sc-if\s+value="\{\{\s*([^}]+?)\s*\}\}"[^>]*>|<\/sc-if>|<sc-for\s+list="\{\{\s*([^}]+?)\s*\}\}"\s+as="(\w+)"[^>]*>|<\/sc-for>|\{\{\s*([^}]+?)\s*\}\}|`|\$\{/g;
  let last = 0;
  let m;
  const expr = (e) => {
    if (/^(true|false|null|-?\d+(\.\d+)?)$/.test(e)) return e;
    const root = e.split('.')[0];
    return loopVars.includes(root) ? e : `v.${e}`;
  };
  while ((m = re.exec(markup))) {
    out += markup.slice(last, m.index);
    last = re.lastIndex;
    const t = m[0];
    if (t.startsWith('<sc-if')) { out += '${(' + expr(m[1]) + ') ? `'; stack.push('if'); }
    else if (t === '</sc-if>') { stack.pop(); out += "` : ''}"; }
    else if (t.startsWith('<sc-for')) { out += '${(' + expr(m[2]) + ' || []).map((' + m[3] + ') => `'; loopVars.push(m[3]); stack.push('for'); }
    else if (t === '</sc-for>') { stack.pop(); loopVars.pop(); out += "`).join('')}"; }
    else if (t === '`') out += '\\`';
    else if (t === '${') out += '\\${';
    else out += '${' + expr(m[4]) + '}';
  }
  out += markup.slice(last);
  if (stack.length) throw new Error('unbalanced control tags');
  return out;
}

for (const file of readdirSync(SRC).filter((f) => f.endsWith('.dc.html'))) {
  const name = file.replace('.dc.html', '');
  const html = readFileSync(join(SRC, file), 'utf8');
  const body = html.slice(html.indexOf('<x-dc>') + 6, html.indexOf('</x-dc>')).replace(/<helmet>[\s\S]*?<\/helmet>/, '').trim();
  const script = html.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
  const js = `// Generated by scripts/convert-art.mjs from design/components/${file} — do not edit by hand.
/* eslint-disable */
class DCLogic { constructor(props) { this.props = props || {}; this.state = {}; } setState() {} }
${script.trim()}
const tpl = (v) => \`${convertMarkup(body)}\`;
export default function render(props = {}) {
  const v = new Component(props).renderVals();
  return tpl(v);
}
`;
  writeFileSync(join(OUT, name + '.js'), js);
  console.log('art:', name);
}
